### ISSUE TITLE
Support for Flatcar

### ISSUE THREAD

**Issue by alban** [rancher-sandbox/lockc-helm-charts#9]
Hi!

When testing the helm chart on Flatcar, I get the following error and the daemonset does not start:

```
        message: 'error while creating mount source path ''/usr/local/bin/runc'':
          mkdir /usr/local/bin/runc: read-only file system'
        reason: ContainerCannotRun
```

On Flatcar, `/usr/local/bin/runc` does not exist and the path is on a read-only filesystem.

Initially, I could workaround this issue by setting the volume on a parent directory instead:
* `/usr` -> `/host/usr`

But it is not enough because the `runc` used on Flatcar is installed at `/run/torcx/unpack/docker/bin/runc`. So I tried to use the following host volume in the lockc daemon set:
* `/run/torcx/unpack/docker/bin/runc` -> `/host/usr/bin/runc`

In this way, lockc fanotify code successfully picks up runc events.

Alternatively, `/run/torcx/unpack/docker/bin/runc` could be added in [lockc/src/runc.rs](https://github.com/rancher-sandbox/lockc/blob/7cb45b8a014f814c0eb3efe4bab1c6cfbb6dd71f/lockc/src/runc.rs#L342-L349). This is the way that Inspektor Gadget did it in its runcfanotify package [pkg/runcfanotify/runcfanotify.go](https://github.com/kinvolk/inspektor-gadget/blob/40b27d56ec9d9fd9d0871b0d7f390d998be639fa/pkg/runcfanotify/runcfanotify.go#L78-L88).

Do you have a preference which approach to use to fix this issue?

cc @vadorovsky

**Comment by vadorovsky** [comment]
I don't mind adding `/run/torcx/unpack/docker/bin/runc` to runc.rs. I will submit a PR soon.
